export const WELCOME = 'WELCOME';
export const ERRORS = 'SUBSCRIPTION_ERRORS';
export const LOGIN = 'SUBSCRIBER_LOGIN';
export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const SUBSCRIPTION_TOKEN = 'AUTH_SUBSCRIPTION_TOKEN';
