export const ERRORS = 'SUBJECT_ERRORS';
export const VIEW_ALL_SUBJECT = 'VIEW_ALL_SUBJECT';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
